export const SET_NEW_USER_MODAL_IS_OPEN = "SET_NEW_USER_MODAL_IS_OPEN";

export const POST_NEW_USER_START = "POST_NEW_USER_START";
export const POST_NEW_USER_SUCCESS = "POST_NEW_USER_SUCESS";
export const POST_NEW_USER_ERROR = "POST_NEW_USER_ERROR";

export const FETCH_ALL_USERS_START = "FETCH_ALL_USERS_START";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_ERROR = "FETCH_ALL_USERS_ERROR";

export const SET_NEW_TRIP_MODAL_IS_OPEN = "SET_NEW_TRIP_MODAL_IS_OPEN";

export const POST_NEW_TRIP_START = "POST_NEW_TRIP_START";
export const POST_NEW_TRIP_SUCCESS = "POST_NEW_TRIP_SUCCESS";
export const POST_NEW_TRIP_ERROR = "POST_NEW_TRIP_ERROR";

export const FETCH_ALL_TRIPS_START = "FETCH_ALL_TRIPS_START";
export const FETCH_ALL_TRIPS_SUCCESS = "FETCH_ALL_TRIPS_SUCCESS";
export const FETCH_ALL_TRIPS_ERROR = "FETCH_ALL_TRIPS_ERROR";

export const SET_IS_BUSY = "SET_IS_BUSY";

export const SET_ERROR = "SET_ERROR";

export const POST_RIDE_REQUEST_START = "POST_RIDE_REQUEST_START";
export const POST_RIDE_REQUEST_SUCCESS = "POST_RIDE_REQUEST_SUCESS";

export const SET_SNACKBAR_IS_OPEN = "SET_SNACKBAR_IS_OPEN";
