export const SET_NEW_USER_MODAL_IS_OPEN = "SET_NEW_USER_MODAL_IS_OPEN";

export const POST_NEW_USER_START = "POST_NEW_USER_START";
export const POST_NEW_USER_SUCCESS = "POST_NEW_USER_SUCESS";
export const POST_NEW_USER_ERROR = "POST_NEW_USER_ERROR";

export const FETCH_ALL_USERS_START = "FETCH_ALL_USERS_START";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_ERROR = "FETCH_ALL_USERS_ERROR";

export const SET_NEW_TRIP_MODAL_IS_OPEN = "SET_NEW_TRIP_MODAL_IS_OPEN";

export const POST_NEW_TRIP_START = "POST_NEW_TRIP_START";
export const POST_NEW_TRIP_SUCCESS = "POST_NEW_TRIP_SUCCESS";
export const POST_NEW_TRIP_ERROR = "POST_NEW_TRIP_ERROR";

export const FETCH_ALL_TRIPS_START = "FETCH_ALL_TRIPS_START";
export const FETCH_ALL_TRIPS_SUCCESS = "FETCH_ALL_TRIPS_SUCCESS";
export const FETCH_ALL_TRIPS_ERROR = "FETCH_ALL_TRIPS_ERROR";
export const FETCH_ALL_MY_TRIPS_SUCCESS = "FETCH_ALL_MY_TRIPS_SUCCESS";

export const SET_IS_BUSY = "SET_IS_BUSY";

export const SET_ERROR = "SET_ERROR";

export const SET_SNACKBAR_IS_OPEN = "SET_SNACKBAR_IS_OPEN";

export const SET_SELECTED_TRIP = "SET_SELECTED_TRIP";
export const SET_OFFER_RIDE_MODAL_IS_OPEN = "SET_OFFER_RIDE_MODAL_IS_OPEN";
export const SET_REQUEST_RIDE_MODAL_IS_OPEN = "SET_REQUEST_RIDE_MODAL_IS_OPEN";

export const SET_USER_TO_OFFER = "SET_USER_TO_OFFER";
export const SET_USER_TO_REQUEST_FROM = "SET_USER_TO_REQUEST_FROM";

export const POST_RIDE_OFFER_SUCCESS = "POST_RIDE_OFFER_SUCCESS";
export const POST_RIDE_REQUEST_SUCCESS = "POST_RIDE_REQUEST_SUCCESS";

export const FETCH_ALL_RIDE_REQUESTS_SUCCESS = 'FETCH_ALL_RIDE_REQUESTS_SUCCESS'
export const FETCH_ALL_RIDE_OFFERS_SUCCESS = 'FETCH_ALL_RIDE_OFFERS_SUCCESS';
